baseURL = "https://example.com/"
title = "Salinger Theme"
# theme = "salinger"

[params]

author = "John Doe"
#googleAnalytics = ""
twemoji = true
text404 = "Since the page you were looking for seems like doesn't exist, we <strong>strongly</strong> suggest you to better investigate the URL and/or go back to the <a href=\"/\">home</a>."

DateFormat = "Jan 2006"

mainMenuSvg = '''
<svg class="icon w-7 h-7" xmlns="http://www.w3.org/2000/svg" height="48" viewBox="0 -960 960 960" width="48"><path d="M110-558q-12.75 0-21.375-8.625T80-588v-10q0-109 105-175.5T480-840q190 0 295 66.5T880-598v10q0 12.75-8.625 21.375T850-558H110Zm32-60h676q-3-69-96.5-115.5T480-780q-148 0-242.5 46.5T142-618ZM80-416q0-8.878 7-17.439T105-447q23-8 45.564-23.5T216-486q54 0 71.5 22t58.5 22q41 0 60.5-22t73.5-22q54 0 73.5 22t60.5 22q41 0 58.5-22t71.5-22q43 0 65.5 15.5T855-447q11.184 5.25 18.092 13.125Q880-426 880-416q0 15.162-10.5 24.081Q859-383 846-386q-32-8-50.5-24t-51.515-16Q703-426 685.5-404T614-382q-54 0-73.5-22T480-426q-41 0-60.5 22T346-382q-54 0-71.5-22t-58.485-22Q183-426 164.5-410T114-386q-13 3-23.5-5.919T80-416Zm60 296q-24 0-42-18t-18-42v-68q0-24.75 17.625-42.375T140-308h680q24.75 0 42.375 17.625T880-248v68q0 24-18 42t-42 18H140Zm0-60h680v-68H140v68Zm2-438h676-676Zm-2 370h680-680Z"/></svg>
'''

logoSvg = '''
<svg xmlns="http://www.w3.org/2000/svg" height="40" viewBox="0 -960 960 960" width="40"><path d="M292-506q18-36 38.5-71t43.5-67l-79-16-109 109 106 45Zm515-312q-102 5-184 43.5T463-658q-31 31-64 81t-59 107l133 133q57-26 107-59t81-64q78-78 116.5-159.5T821-803q0-3-1-6t-3-5q-2-2-4.5-3t-5.5-1ZM570-566q-20-20-20-49.5t20-49.5q20-20 49.5-20t49.5 20q20 20 20 49.5T669-566q-20 20-49.5 20T570-566Zm-61 278 45 105 109-109-15-79q-32 23-67.5 44T509-288Zm373-559q3 125-40.5 230.5T704-417q-1 1-2 1.5t-2 1.5l22 110q3 15-1 29t-15 25L565-109q-11 11-26.5 8T517-119l-68-157-169-170-158-67q-15-6-17.5-22t8.5-27l140-140q11-11 25-15.5t29-1.5l110 22q1-1 2-1.5t2-1.5q94-94 199-137.5T850-878q6 0 11.5 2.5T872-868q5 5 7.5 10t2.5 11ZM149-325q35-35 85.5-35.5T320-326q35 35 34.5 85.5T319-155q-26 26-80.5 43T75-80q15-109 31.5-164t42.5-81Zm42 43q-14 15-25 47t-19 82q50-8 82-19t47-25q19-17 19.5-42.5T278-284q-19-18-44.5-17.5T191-282Z"/></svg>
'''
logoLabel = "Salinger Theme"

mainMenuShowThemes = true
showFooterOnHomepage = true
showHeaderOnHomepage = true
showSocialOnHomepage = true
showOnlyFeaturedPost = true

[params.meta]
title = "Salinger Theme for Hugo built with TailwindCSS and DaisyUI"
description = "Salinger is a clean, minimalistic, mobile-first, blazing-fast, fancy and lightweight theme for the Hugo framework built with TailwindCSS and DaisyUI"
keywords = ["simple", "minimal", "clean", "fast", "blog", "portfolio", "responsive", "twemoji", "recursion", "section", "tailwind", "daisyui"]

[params.footer]
copy = 'John Doe. <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" class="link">Some rights reserved.</a>'

[[params.social]]
name = "github"
url = "https://github.com/jacksalici/salinger-theme"
icon = "fa-brands fa-github"
featured = true # true to be displayed in the home hero.

[Menu]
[[menu.main]]
name = "Projects."
url = "/projects/"
weight = 1

[[menu.main]]
name = "Contact me."
url = "mailto:mail@mail.com"
weight = 2

[[menu.footer]]
name = "Privacy Policy"
url = "/privacy"
weight= 1 

[taxonomies]
category = "categories"
lang = "langs"
tags = "tags"
tool = "tools"


#Â the following code is mandatory for the theme to work properly.

[module]
[module.hugoVersion]
extended = false
min = "0.112.0"
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"

[build]
writeStats = true
[[build.cachebusters]]
source = "assets/watching/hugo_stats\\.json"
target = "styles\\.css"
[[build.cachebusters]]
source = "(postcss|tailwind)\\.config\\.js"
target = "css"
[[build.cachebusters]]
source = "assets/.*\\.(js|ts|jsx|tsx)"
target = "js"
[[build.cachebusters]]
source = "assets/.*\\.(.*)$"
target = "$1"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = 'base16-snazzy'